version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5501:5501"
    environment:
      - PORT=5501
      - MONGO_URI=mongodb://mongo:27017/formbuilderDB
    depends_on:
      - mongo

  frontend:
    build: ./app
    ports:
      - "5173:5173"
    environment:
      - PORT=5173

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
