version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: formbuilder-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: formbuilder-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - PORT=5501
      - MONGO_URI=mongodb://mongo:27017/formbuilderDB
    depends_on:
      - mongo
    ports:
      - "5501:5501"

  frontend:
    build: ./app
    container_name: formbuilder-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
